application:
  runtimeManifest:
    packages:
      aio-commerce-shipstation-app:
        license: Apache-2.0
        actions:
          api-mesh-query-content:
            function: src/api-mesh/actions/api-mesh-query-content/index.js
            web: 'yes'
            runtime: nodejs:16
            inputs:
              MESH_ID: $MESH_ID
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          shipstation-shipping:
            function: src/api-mesh/actions/shipstation-shipping/index.js
            web: 'yes'
            runtime: nodejs:16
            annotations:
              require-adobe-auth: false
            inputs:
              SHIPSTATION_API_KEY: $SHIPSTATION_API_KEY
              LOG_LEVEL: debug
