application:
  runtimeManifest:
    packages:
      aio-commerce-shipstation-app:
        license: Apache-2.0
        actions:
          shipstation-shipping:
            function: src/app/actions/shipstation-shipping/index.js
            web: "raw"
            runtime: nodejs:22
            annotations:
              require-adobe-auth: false
extensions:
  commerce/backend-ui/1:
    $include: src/commerce-backend-ui-1/ext.config.yaml
operations:
  view:
    - type: web
      impl: web
web: 'yes'
inputs:
  LOG_LEVEL: debug
annotations:
  require-adobe-auth: false
