operations:
  view:
    - type: web
      impl: index.html
actions: actions
web: web-src
runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        registration:
          function: actions/registration/index.js
          web: "yes"
          runtime: "nodejs:22"
          inputs:
            LOG_LEVEL: debug
          annotations:
            require-adobe-auth: true
            final: true
    shipstation:
      license: Apache-2.0
      actions:
        admin-config:
          function: actions/admin-config/index.js
          web: "yes"
          runtime: "nodejs:22"
          inputs:
            LOG_LEVEL: debug
            OAUTH_CLIENT_ID: $OAUTH_CLIENT_ID
            OAUTH_CLIENT_SECRETS: $OAUTH_CLIENT_SECRETS
            OAUTH_TECHNICAL_ACCOUNT_ID: $OAUTH_TECHNICAL_ACCOUNT_ID
            OAUTH_TECHNICAL_ACCOUNT_EMAIL: $OAUTH_TECHNICAL_ACCOUNT_EMAIL
            OAUTH_SCOPES: $OAUTH_SCOPES
            OAUTH_IMS_ORG_ID: $OAUTH_IMS_ORG_ID
            ENCRYPTION_KEY: $ENCRYPTION_KEY
            ENCRYPTION_IV: $ENCRYPTION_IV
            RUNTIME_NAMESPACE: $AIO_RUNTIME_NAMESPACE
          annotations:
            require-adobe-auth: true
            final: true
            web: "yes"
        shipstation-shipping:
          function: actions/shipstation-shipping/index.js
          runtime: nodejs:22
          web: "yes"
          annotations:
            require-adobe-auth: false
            raw-http: true
            final: true
            web: "yes"
