runtimeManifest:
  packages:
    admin-ui-sdk:
      license: Apache-2.0
      actions:
        registration:
          function: actions/registration/index.js
          runtime: nodejs:22
          web: 'yes'
          annotations:
            require-adobe-auth: false
            final: true