name: Deploy to PaaS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to PaaS
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        node-version: ["20"]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: Setup CLI
        uses: adobe/aio-cli-setup-action@1.3.0
        with:
          os: ${{ matrix.os }}
          version: 10.x.x
      - name: Auth
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: oauth_sts
          CLIENTID: ${{ vars.CLIENTID_PAAS }}
          CLIENTSECRET: ${{ secrets.CLIENTSECRET_PAAS }}
          TECHNICALACCOUNTID: ${{ vars.TECHNICALACCID_PAAS }}
          TECHNICALACCOUNTEMAIL: ${{ vars.TECHNICALACCEMAIL_PAAS }}
          IMSORGID: ${{ vars.IMSORGID_PAAS }}
          SCOPES: ${{ vars.SCOPES_PAAS }}
      - name: Build
        env:
          AIO_RUNTIME_NAMESPACE: ${{ vars.AIO_RUNTIME_NAMESPACE_PAAS }}
          COMMERCE_WEBHOOKS_PUBLIC_KEY: ${{ vars.COMMERCE_WEBHOOKS_PUBLIC_KEY_PAAS }}
          COMMERCE_ENDPOINT: ${{ vars.COMMERCE_ENDPOINT }}
          SHIPSTATION_API_KEY: ${{ vars.SHIPSTATION_API_KEY }}
          SHIPSTATION_CARRIER_IDS: ${{ vars.SHIPSTATION_CARRIER_IDS }}
          SHIPSTATION_WAREHOUSE_NAME: ${{ vars.SHIPSTATION_WAREHOUSE_NAME }}
          SHIPSTATION_WAREHOUSE_PHONE: ${{ vars.SHIPSTATION_WAREHOUSE_PHONE }}
          SHIPSTATION_WAREHOUSE_ADDRESS_LINE1: ${{ vars.SHIPSTATION_WAREHOUSE_ADDRESS_LINE1 }}
          SHIPSTATION_WAREHOUSE_CITY: ${{ vars.SHIPSTATION_WAREHOUSE_CITY }}
          SHIPSTATION_WAREHOUSE_REGION: ${{ vars.SHIPSTATION_WAREHOUSE_REGION }}
          SHIPSTATION_WAREHOUSE_POSTCODE: ${{ vars.SHIPSTATION_WAREHOUSE_POSTCODE }}
          SHIPSTATION_WAREHOUSE_COUNTRY: ${{ vars.SHIPSTATION_WAREHOUSE_COUNTRY }}
          SHIPSTATION_SHIPTO_NAME: ${{ vars.SHIPSTATION_SHIPTO_NAME }}
          SHIPSTATION_SHIPTO_PHONE: ${{ vars.SHIPSTATION_SHIPTO_PHONE }}
          SHIPSTATION_DEBUGGING: ${{ vars.SHIPSTATION_DEBUGGING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: build
      - name: Deploy
        env:
          AIO_RUNTIME_NAMESPACE: ${{ vars.AIO_RUNTIME_NAMESPACE_PAAS }}
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_PAAS }}
          AIO_PROJECT_ID: ${{ vars.AIO_PROJECT_ID_PAAS }}
          AIO_PROJECT_NAME: ${{ vars.AIO_PROJECT_NAME_PAAS }}
          AIO_PROJECT_ORG_ID: ${{ vars.AIO_PROJECT_ORG_ID_PAAS }}
          AIO_PROJECT_WORKSPACE_ID: ${{ vars.AIO_PROJECT_WORKSPACE_ID_PAAS }}
          AIO_PROJECT_WORKSPACE_NAME: ${{ vars.AIO_PROJECT_WORKSPACE_NAME_PAAS }}
          AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ vars.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES_PAAS }}
          COMMERCE_WEBHOOKS_PUBLIC_KEY: ${{ vars.COMMERCE_WEBHOOKS_PUBLIC_KEY_PAAS }}
          COMMERCE_ENDPOINT: ${{ vars.COMMERCE_ENDPOINT }}
          SHIPSTATION_API_KEY: ${{ vars.SHIPSTATION_API_KEY }}
          SHIPSTATION_CARRIER_IDS: ${{ vars.SHIPSTATION_CARRIER_IDS }}
          SHIPSTATION_WAREHOUSE_NAME: ${{ vars.SHIPSTATION_WAREHOUSE_NAME }}
          SHIPSTATION_WAREHOUSE_PHONE: ${{ vars.SHIPSTATION_WAREHOUSE_PHONE }}
          SHIPSTATION_WAREHOUSE_ADDRESS_LINE1: ${{ vars.SHIPSTATION_WAREHOUSE_ADDRESS_LINE1 }}
          SHIPSTATION_WAREHOUSE_CITY: ${{ vars.SHIPSTATION_WAREHOUSE_CITY }}
          SHIPSTATION_WAREHOUSE_REGION: ${{ vars.SHIPSTATION_WAREHOUSE_REGION }}
          SHIPSTATION_WAREHOUSE_POSTCODE: ${{ vars.SHIPSTATION_WAREHOUSE_POSTCODE }}
          SHIPSTATION_WAREHOUSE_COUNTRY: ${{ vars.SHIPSTATION_WAREHOUSE_COUNTRY }}
          SHIPSTATION_SHIPTO_NAME: ${{ vars.SHIPSTATION_SHIPTO_NAME }}
          SHIPSTATION_SHIPTO_PHONE: ${{ vars.SHIPSTATION_SHIPTO_PHONE }}
          SHIPSTATION_DEBUGGING: ${{ vars.SHIPSTATION_DEBUGGING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}

        uses: adobe/aio-apps-action@3.3.0
        with:
          os: ${{ matrix.os }}
          command: deploy
          noPublish: true
      - name: Show .env, .aio, and environment variables
        env:
          AIO_RUNTIME_NAMESPACE: ${{ vars.AIO_RUNTIME_NAMESPACE_PAAS }}
          AIO_RUNTIME_AUTH: ${{ secrets.AIO_RUNTIME_AUTH_PAAS }}
          AIO_PROJECT_ID: ${{ vars.AIO_PROJECT_ID_PAAS }}
          AIO_PROJECT_NAME: ${{ vars.AIO_PROJECT_NAME_PAAS }}
          AIO_PROJECT_ORG_ID: ${{ vars.AIO_PROJECT_ORG_ID_PAAS }}
          AIO_PROJECT_WORKSPACE_ID: ${{ vars.AIO_PROJECT_WORKSPACE_ID_PAAS }}
          AIO_PROJECT_WORKSPACE_NAME: ${{ vars.AIO_PROJECT_WORKSPACE_NAME_PAAS }}
          AIO_PROJECT_WORKSPACE_DETAILS_SERVICES: ${{ vars.AIO_PROJECT_WORKSPACE_DETAILS_SERVICES_PAAS }}
          COMMERCE_WEBHOOKS_PUBLIC_KEY: ${{ vars.COMMERCE_WEBHOOKS_PUBLIC_KEY_PAAS }}
          COMMERCE_ENDPOINT: ${{ vars.COMMERCE_ENDPOINT }}
          SHIPSTATION_API_KEY: ${{ vars.SHIPSTATION_API_KEY }}
          SHIPSTATION_CARRIER_IDS: ${{ vars.SHIPSTATION_CARRIER_IDS }}
          SHIPSTATION_WAREHOUSE_NAME: ${{ vars.SHIPSTATION_WAREHOUSE_NAME }}
          SHIPSTATION_WAREHOUSE_PHONE: ${{ vars.SHIPSTATION_WAREHOUSE_PHONE }}
          SHIPSTATION_WAREHOUSE_ADDRESS_LINE1: ${{ vars.SHIPSTATION_WAREHOUSE_ADDRESS_LINE1 }}
          SHIPSTATION_WAREHOUSE_CITY: ${{ vars.SHIPSTATION_WAREHOUSE_CITY }}
          SHIPSTATION_WAREHOUSE_POSTCODE: ${{ vars.SHIPSTATION_WAREHOUSE_POSTCODE }}
          SHIPSTATION_WAREHOUSE_COUNTRY: ${{ vars.SHIPSTATION_WAREHOUSE_COUNTRY }}
          SHIPSTATION_SHIPTO_NAME: ${{ vars.SHIPSTATION_SHIPTO_NAME }}
          SHIPSTATION_SHIPTO_PHONE: ${{ vars.SHIPSTATION_SHIPTO_PHONE }}
          SHIPSTATION_DEBUGGING: ${{ vars.SHIPSTATION_DEBUGGING }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
        run: |
          echo "---- .env ----"
          if [ -f .env ]; then
            cat .env
          else
            echo ".env file does not exist."
          fi
          echo "---- .aio ----"
          if [ -f .aio ]; then
            cat .aio
          else
            echo ".aio file does not exist."
          fi
          echo "---- Environment Variables ----"
          printenv
